site_name: SoUI 官方文档
site_description: C++ 快速设计界面库
site_author: SoUI Team
site_url: https://X.org/en/
repo_name: 2926295173/SoUIDocs
repo_url: https://github.com/2926295173/SoUIDocs
edit_uri: blob/main/docs/zh/docs/
copyright: Copyright &copy; 2010 - 2021 SoUI Team
theme:
  name: material
  language: en
  palette:
    primary: white
    accent: blue
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: https://X.org/static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- Start:
  - index.md
  - discussion.md
  - theme.md
  - Show/show.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  alternate:
  - link: /
    name: 中文
  - link: /en/
    name: English
  copyright: CC BY-NC-SA 4.0
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- https://X.org/static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- https://X.org/static/css/extra.css
